### PR TITLE
ported to scala 2.13.1

### PR DESCRIPTION
**Pull request by torstenrudolf**
Hi there, I really like what you did here and use this lib for a toy project.

I ported this project to scala 2.13.1 and would love to have it published to maven.

The main change has to do with the refactored scala.collection in 2.13. 
I tried to keep the changes to the code as minimal as possible.

### CODE REVIEW

**Comment by GuillaumeDD** [comment]
Hi ! Thank you for your contribution ! Much appreciated !

I ran the benchmarks and found something weird. It appears that the 2.13.1 version introduces a non-linearity w.r.t. the 2.11.12 version (and also that the 2.12 version seems to be unusable).

Any idea where the non-linearity might come from?

Steps to reproduce : 
```sh
$ sbt
> ++2.11.12   # or 2.13.1
> test:run
Multiple main classes detected, select one to run:

 [1] gstlib.benchmark.GeneralizedSuffixTreeBuilderLinearityBenchmark
 [2] gstlib.benchmark.TokenSequenceLinearityBenchmark

# Select the test
```

## Results for `gstlib.benchmark.TokenSequenceLinearityBenchmark`
| Tokens | time<br/>2.11.12 | time <br/>2.13.1   | 
| :---:       | :---        | :---         |
88 | 0.7850688 | 0.2968566
168 | 1.1207547999999998 | 0.5544636000000001
334 | 2.16939 | 2.176759
787 | 4.1098146 | 6.411166400000001
1616 | 9.8288578 | 26.555888200000005
3338 | 34.88326959999999 | 93.83439139999999
7320 | 24.735378400000002 | 416.1573128
16490 | 38.8122908 | 1957.8929578
33350 | 74.771517 | 10658.8537698
67577 | 289.915846 | 44240.0559028
135936 | 580.6151716 |  

2020-04-10-non-linearity

**Comment by torstenrudolf** [comment]
Thanks for checking this so quickly. Sorry, should have picked this up...
Will have a look into this.

**Comment by torstenrudolf** [comment]
I found the problem I think. In scala 2.13 the implicit conversion from arrays to sequence is implemented via copying by default. changed the code so we do the conversion by unsafe wrapping.
Looking at the benchmarks, they are just as fast now and show linear increase in time.

On the other issue with 2.12, could you please elaborate your issue? They seem to run fine for me. Even before this change.

**Comment by torstenrudolf** [comment]
I'm wondering now, that this change potentially breaks some usage of gstlib in case a user changes from 2.11/2.12 to 2.13, without using the unsafe wrapping for arrays.
Do you have an idea how to mitigate this? Very annoying to have this default implicit conversion-by-copying in scope automatically.

**Comment by GuillaumeDD** [comment]
First, thank you for this nice contribution! Hoping to merge it!

Regarding the 2.12 issue, it was due to a wrong javac version on my machine.

Regarding the unsage wrapping for arrays, it looks like the problem is coming from a change in the semantics of `scala.Seq` which referred to a possibly-mutable collection in scala <= 2.12 and is now referring to a strictly immutable collection in scala >= 2.13.
In order to restore a cross-version semantics, it turns out that `Seq` has to be changed for `collection.Seq` that is referring to a possibly-mutable collection in both scala <= 2.12 and scala >= 2.13.

I am working on a fix in that direction. I'll keep you informed!

**Comment by GuillaumeDD** [comment]
It looks like it's working seamlessly between all scala versions without the need for implicit.

What about this alternative ?

**Comment by torstenrudolf** [comment]
Great! That's much better!

**Comment by GuillaumeDD** [comment]
Thank again you for your contribution!

If it is possible, I would be curious to see your toy project :-)

**Pull request merged**
